### ISSUE TITLE
[PE-D] Skill field of Person allows duplicate

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W13-3/tp#110]
The skills field of person can have duplicate names, and this has a slightly weird behaviour with sort:

Person list sorted by Bash, with one Person having duplicate Bash skills with different proficiency values:
![image.png](https://raw.githubusercontent.com/weijuey/ped/main/files/decd38cb-8806-4fa9-aa98-811924f642f4.png)

Skill should not allow duplicate skill names.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: weijuey/ped#5

**Comment by tzhan98** [comment]
See also: Issue https://github.com/AY2122S2-CS2103T-W13-3/tp/issues/130
