### ISSUE TITLE
[PE-D] Not sure of the difference between filter and sort

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W13-3/tp#121]
![Screenshot 2022-04-01 at 6.35.27 PM.png](https://raw.githubusercontent.com/vanessaxuuan/ped/main/files/0ec7690e-d37e-4a60-84f2-e2a0dde3e86c.png)

VS

![Screenshot 2022-04-01 at 6.35.42 PM.png](https://raw.githubusercontent.com/vanessaxuuan/ped/main/files/8d025b44-3bed-446a-a383-57a5b5458d13.png)

However, how is the skill proficiency determined if the input for skills are all the same? 

Perhaps sort could be included as [Upcoming] in user guide, or an explanation on skill proficiency level could be added

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: vanessaxuuan/ped#4

**Comment by tzhan98** [comment]
Update documentation regarding skill color indication and number of arguments for sort and filter
