### ISSUE TITLE
[PE-D] Long `skills tag` causes all other `skills tag` to be not visible on the GUI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W13-3/tp#135]
After adding a very long skill tag, all other skills tags are now not visible.

![image.png](https://raw.githubusercontent.com/YiHern-Lee/ped/main/files/cc05a512-c497-4380-8ab1-733ebabc5e9f.png)

### Steps to reproduce:
1. Add a short and valid `skill tag` to user
2. Add an extremely long `skill tag` to user
3. Filter by original short `skill tag` to retrieve user's profile and guarantee that user has that particular `skill tag`
4. That particular `skill tag` is no longer visible

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: YiHern-Lee/ped#13

**Comment by tzhan98** [comment]
Solution: Limit length of skill name

**Comment by tzhan98** [comment]
Related to Issue https://github.com/AY2122S2-CS2103T-W13-3/tp/issues/133
