### ISSUE TITLE
Add tag 'skill'

### ISSUE THREAD

**Issue by tzhan98** [AY2122S2-CS2103T-W13-3/tp#18]
Add skeleton of `skill` feature

**Comment by tzhan98** [comment]
I changed the assert() method in `JsonSerializableAddressBookTest::toModelType_typicalPersonsFile_success()` to compare String values instead of addressbook. Does comparing string values undermine the integrity of the testcase?

Instead of : 
`assertEquals(addressBookFromFile., typicalPersonsAddressBook);`
I am now using:
`assertEquals(addressBookFromFile.toString(), typicalPersonsAddressBook.toString());`

**Comment by MelvinCZJ** [comment]
I think you can proceed to merge.
