### ISSUE TITLE
AssertFailure on JsonSerializableAddressBookTest.java

### ISSUE THREAD

**Issue by alexteo98** [AY2122S2-CS2103T-W13-3/tp#34]
Summary:
AssertFailure on `JsonSerializableAddressBookTest.java::toModelType_typicalPersonsFile_success()`.

When using `assertEquals(addressBookFromFile, typicalPersonsAddressBook);` instead of `assertEquals(addressBookFromFile.toString(), typicalPersonsAddressBook.toString());`, assertFailure is thrown and test fails.

Details:
Persons in `addressBookFromFile` differs from Persons in `typicalPersonsAddressBook`.
Likely caused by not matching information in `TypicalPersons.java` and `typicalPersonsAddressBook.json`

![image](https://user-images.githubusercontent.com/59075695/156873908-41add5d2-5166-4b0f-a2dc-e6cfca8a61cc.png)

**Comment by tzhan98** [comment]
My bad, I was the one who edited this test case to compare strings instead. 
This bug has to do with `PersonBuilder.java` where default `skill` and `tag` were added to every `person` in the constructor.
